---
- name: Create Proxmox VM
  connection: local
  hosts: localhost
  roles:
    - role: clone
    - role: config
    - role: start
    # - role: stop
    # - role: delete
  vars:
    proxmox_password: # Please add proxmox password here
    vm_name: my-vm
    vm_id: 101
    vm_cores: 2
    vm_memory_in_gb: 2
    vm_disk_size: 10G
    vm_ip: 192.168.4.11
