---
- name: Delete VM
  proxmox_kvm:
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ proxmox_host }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ vm_id }}"
    state: absent
    timeout: "{{ vm_timeout }}"
