---
- name: Register Public SSH Key
  slurp:
    src: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
  register: id_rsa_pub

- name: Update IP and SSH Key
  uri:
    url: "https://{{ proxmox_host }}:8006/api2/json/nodes/{{ proxmox_node }}/qemu/{{ vm_id }}/config"
    validate_certs: no
    method: PUT
    headers: 
      Cookie: "PVEAuthCookie={{ auth.json.data.ticket }}"
      CSRFPreventionToken: "{{ auth.json.data.CSRFPreventionToken }}"
    body_format: form-urlencoded
    body:
      sshkeys: "{{ id_rsa_pub['content'] | b64decode | urlencode | replace('/','%2F') }}"
      ipconfig0: "ip={{ vm_ip }}/24,gw={{ vm_gateway_ip }}"
